server:
  port: 8888

# 短信平台的apikey
dingdong:
  apikey: 902c31ebe92cf91985adc56df1054f4a

# Redis服务器地址
spring:
  redis:
    host: 127.0.0.1
# Redis服务器连接端口
    port: 6379
# Redis服务器连接密码（默认为空）
    password:
  datasource:
    url: jdbc:mysql://localhost:3306/phone_message?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useSSL=false
    username: root
    password: 12345678
    driver-class-name: com.mysql.jdbc.Driver

# 日志信息
logging:
  file: ./spring.log
  level:
    com:
      software: DEBUG

mybatis:
  typeAliasesPackage: com.software.phone.dao
  mapperLocations: classpath:mapper/*.xml